#!/usr/bin/env bash
# Regenerates src/sys.rs from libghostty-vt's C headers. Run it after moving
# the Ghostty pin in build.rs, against a checkout of the pinned commit:
#
#   scripts/bindgen.sh /path/to/ghostty
#
# Needs bindgen 0.72 (`cargo install bindgen-cli`) and rustfmt on PATH.
#
# One src/sys.rs serves every target, so the script also generates the
# bindings for x86_64-pc-windows-msvc and fails if they differ: Windows is
# LLP64 (`long` is 32 bits) and MSVC makes every C enum an `int`, either of
# which would change a type or layout. That pass uses clang's own
# freestanding headers, since the host's libc headers do not describe
# Windows.
set -euo pipefail

ghostty=${1:?usage: bindgen.sh GHOSTTY_CHECKOUT}
crate=$(cd "$(dirname "$0")/.." && pwd)
tmp=$(mktemp -d)
wrapper=$tmp/wrapper.h
# GHOSTTY_STATIC: the headers' declarations for linking the static archive
# (no dllimport on Windows).
printf '#define GHOSTTY_STATIC\n#include <ghostty/vt.h>\n' >"$wrapper"

generate() {
  bindgen "$wrapper" \
    --rust-target 1.85 --rust-edition 2024 \
    --allowlist-function 'ghostty_.*' \
    --allowlist-type 'Ghostty.*' \
    --allowlist-var 'GHOSTTY_.*' \
    --default-enum-style consts \
    --no-prepend-enum-name \
    --no-doc-comments \
    -- -I "$ghostty/include" "$@"
}

generate >"$tmp/host.rs"
generate --target=x86_64-pc-windows-msvc -ffreestanding -nostdlibinc >"$tmp/windows.rs"
rustfmt --edition 2024 "$tmp/host.rs" "$tmp/windows.rs"
if ! diff -u "$tmp/host.rs" "$tmp/windows.rs"; then
  echo "bindgen.sh: the Windows (LLP64) bindings differ from the host's; src/sys.rs" \
    "would need per-target bindings" >&2
  exit 1
fi

{
  echo "//! Raw libghostty-vt bindings, generated by scripts/bindgen.sh from the"
  echo "//! headers of the Ghostty commit pinned in build.rs. Do not edit."
  echo
  cat "$tmp/host.rs"
} >"$crate/src/sys.rs"
