#!/usr/bin/env bash
# Regenerates src/sys.rs from libghostty-vt's C headers. Run it after moving
# the Ghostty pin in build.rs, against a checkout of the pinned commit:
#
#   scripts/bindgen.sh /path/to/ghostty
#
# Needs bindgen 0.72 (`cargo install bindgen-cli`) and rustfmt on PATH.
set -euo pipefail

ghostty=${1:?usage: bindgen.sh GHOSTTY_CHECKOUT}
crate=$(cd "$(dirname "$0")/.." && pwd)
wrapper=$(mktemp -d)/wrapper.h
printf '#define GHOSTTY_STATIC\n#include <ghostty/vt.h>\n' >"$wrapper"

{
  echo "//! Raw libghostty-vt bindings, generated by scripts/bindgen.sh from the"
  echo "//! headers of the Ghostty commit pinned in build.rs. Do not edit."
  echo
  bindgen "$wrapper" \
    --rust-target 1.85 --rust-edition 2024 \
    --allowlist-function 'ghostty_.*' \
    --allowlist-type 'Ghostty.*' \
    --allowlist-var 'GHOSTTY_.*' \
    --default-enum-style consts \
    --no-prepend-enum-name \
    --no-doc-comments \
    -- -I "$ghostty/include"
} >"$crate/src/sys.rs"
rustfmt --edition 2024 "$crate/src/sys.rs"
